//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D2RLaunch.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("D2RLaunch.Culture.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act.
        /// </summary>
        public static string ActX {
            get {
                return ResourceManager.GetString("ActX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Monsters Always Drop.
        /// </summary>
        public static string All_Monsters_Always_Drop {
            get {
                return ResourceManager.GetString("All Monsters Always Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language.
        /// </summary>
        public static string AppLang {
            get {
                return ResourceManager.GetString("AppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Language.
        /// </summary>
        public static string AudioLang {
            get {
                return ResourceManager.GetString("AudioLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Extra Files Needed.
        /// </summary>
        public static string AuthorFiles {
            get {
                return ResourceManager.GetString("AuthorFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Backup Characters.
        /// </summary>
        public static string AutoBackup {
            get {
                return ResourceManager.GetString("AutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string AutoBackupBtn1 {
            get {
                return ResourceManager.GetString("AutoBackupBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string AutoBackupBtn2 {
            get {
                return ResourceManager.GetString("AutoBackupBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recent played character and stash backed up successfully!.
        /// </summary>
        public static string AutoBackupSuccess1 {
            get {
                return ResourceManager.GetString("AutoBackupSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recently played character restored successfully!.
        /// </summary>
        public static string AutoBackupSuccess2 {
            get {
                return ResourceManager.GetString("AutoBackupSuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup every 1 hour.
        /// </summary>
        public static string Backup_every_1_hour {
            get {
                return ResourceManager.GetString("Backup every 1 hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup every 15 min.
        /// </summary>
        public static string Backup_every_15_min {
            get {
                return ResourceManager.GetString("Backup every 15 min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup every 30 min.
        /// </summary>
        public static string Backup_every_30_min {
            get {
                return ResourceManager.GetString("Backup every 30 min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup every 5 min.
        /// </summary>
        public static string Backup_every_5_min {
            get {
                return ResourceManager.GetString("Backup every 5 min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By ItemType.
        /// </summary>
        public static string By_Itemtype {
            get {
                return ResourceManager.GetString("By Itemtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Name.
        /// </summary>
        public static string By_Name {
            get {
                return ResourceManager.GetString("By Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Req. Level.
        /// </summary>
        public static string By_Req__Level {
            get {
                return ResourceManager.GetString("By Req. Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion Packs.
        /// </summary>
        public static string Champions {
            get {
                return ResourceManager.GetString("Champions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A Mod.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow you to create a blank mod using only launcher options.\nUse if you&apos;d like a Vanilla experience with additional QoL options.\n\nWould you still like to create your own mod?.
        /// </summary>
        public static string CreateModDesc {
            get {
                return ResourceManager.GetString("CreateModDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations.
        /// </summary>
        public static string Customizations {
            get {
                return ResourceManager.GetString("Customizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow you to change in-game settings to your preference for each difficulty.
        /// </summary>
        public static string CustomizeDesc {
            get {
                return ResourceManager.GetString("CustomizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Customizations.
        /// </summary>
        public static string CustomizeTitle {
            get {
                return ResourceManager.GetString("CustomizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string D2RWebsite {
            get {
                return ResourceManager.GetString("D2RWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string D2RYoutube {
            get {
                return ResourceManager.GetString("D2RYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Density: .
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dize.
        /// </summary>
        public static string Dize {
            get {
                return ResourceManager.GetString("Dize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Mod.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled (Mini).
        /// </summary>
        public static string Enabled__Mini_ {
            get {
                return ResourceManager.GetString("Enabled (Mini)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled (No Orbs).
        /// </summary>
        public static string Enabled__No_Orbs_ {
            get {
                return ResourceManager.GetString("Enabled (No Orbs)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Rate.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Font.
        /// </summary>
        public static string FontBtn {
            get {
                return ResourceManager.GetString("FontBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow you to change the in-game font used. All loot filter icons are included in each font. Fonts will be added by request..
        /// </summary>
        public static string FontDesc {
            get {
                return ResourceManager.GetString("FontDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Font.
        /// </summary>
        public static string FontTitle {
            get {
                return ResourceManager.GetString("FontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Sizes.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDR Fix.
        /// </summary>
        public static string HDR {
            get {
                return ResourceManager.GetString("HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hell.
        /// </summary>
        public static string Hell {
            get {
                return ResourceManager.GetString("Hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Helmets.
        /// </summary>
        public static string HelmetDisplay {
            get {
                return ResourceManager.GetString("HelmetDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Design.
        /// </summary>
        public static string HUD {
            get {
                return ResourceManager.GetString("HUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a mod from a .zip download link:.
        /// </summary>
        public static string InstallLink {
            get {
                return ResourceManager.GetString("InstallLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mod.
        /// </summary>
        public static string InstallMod {
            get {
                return ResourceManager.GetString("InstallMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a mod from the D2RModding database:.
        /// </summary>
        public static string InstallModDB {
            get {
                return ResourceManager.GetString("InstallModDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing your mod into D2R....
        /// </summary>
        public static string InstallProgressD2R {
            get {
                return ResourceManager.GetString("InstallProgressD2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download has started, but web failed to report file size!.
        /// </summary>
        public static string InstallProgressGHSize {
            get {
                return ResourceManager.GetString("InstallProgressGHSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod installed successfully!.
        /// </summary>
        public static string InstallProgressSuccess {
            get {
                return ResourceManager.GetString("InstallProgressSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item + Rune Icons.
        /// </summary>
        public static string Item___Rune_Icons {
            get {
                return ResourceManager.GetString("Item + Rune Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Icons Only.
        /// </summary>
        public static string Item_Icons_Only {
            get {
                return ResourceManager.GetString("Item Icons Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Display.
        /// </summary>
        public static string ItemIcons {
            get {
                return ResourceManager.GetString("ItemIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Item Levels.
        /// </summary>
        public static string Itemlevels {
            get {
                return ResourceManager.GetString("Itemlevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Update Available!.
        /// </summary>
        public static string LauncherUpdateRdy {
            get {
                return ResourceManager.GetString("LauncherUpdateRdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2RLaunch User Data.
        /// </summary>
        public static string LaunchFiles {
            get {
                return ResourceManager.GetString("LaunchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options let you force specific map layouts so you can roll that &apos;perfect&apos; map anytime you want. Details explained below:\n\nTower: The tower entrance is on the same screen as your waypoint.\n\nCatacombs: Levels 3 and 4 are less than 3 screens away\n\nAncient Tunnels: Entrance is 1 screen away from your waypoint\n\nLower Kurast: Very favorable super chest pattern near your waypoint\n\nDurance of Hate: Level 3 entrance is one teleport away from waypoint.\n\nHellforge: Forge is at closest spawn to your w [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MapsInfo {
            get {
                return ResourceManager.GetString("MapsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: These options are meant for a fun experience or two, but will feel like cheating. Use at your own risk.\nIf you would like to proceed, please read these instructions:\n\nStep 1: Start the game with your selected layout\nStep 2: Once loaded into the game with your character fully, EXIT the game.\nStep 3: After exiting the game, you should see your layout dropdown on launcher changed back to Default. This is normal; Start the game again.\n\nIf you do not exit the game after changing your map layout.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MapsSetup {
            get {
                return ResourceManager.GetString("MapsSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merc Identifier.
        /// </summary>
        public static string MercID {
            get {
                return ResourceManager.GetString("MercID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged.
        /// </summary>
        public static string Merged {
            get {
                return ResourceManager.GetString("Merged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Choice.
        /// </summary>
        public static string ModChoice {
            get {
                return ResourceManager.GetString("ModChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Files.
        /// </summary>
        public static string ModFiles {
            get {
                return ResourceManager.GetString("ModFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QoL Options.
        /// </summary>
        public static string ModOptions {
            get {
                return ResourceManager.GetString("ModOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Author hasn&apos;t added support for auto-updates yet!.
        /// </summary>
        public static string ModUpdateAuthor {
            get {
                return ResourceManager.GetString("ModUpdateAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod files are current...no update needed!.
        /// </summary>
        public static string ModUpdateCurrent {
            get {
                return ResourceManager.GetString("ModUpdateCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Update Available!\n\nWould you like to make a backup of your mod folder before updating?.
        /// </summary>
        public static string ModUpdateRdy {
            get {
                return ResourceManager.GetString("ModUpdateRdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Stats Display.
        /// </summary>
        public static string MonsterStatsDisplay {
            get {
                return ResourceManager.GetString("MonsterStatsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Files.
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        public static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Background.
        /// </summary>
        public static string No_Background {
            get {
                return ResourceManager.GetString("No Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Icons.
        /// </summary>
        public static string No_Icons {
            get {
                return ResourceManager.GetString("No Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Discord Found!.
        /// </summary>
        public static string NoDiscord {
            get {
                return ResourceManager.GetString("NoDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster Item Drops.
        /// </summary>
        public static string NoDrop {
            get {
                return ResourceManager.GetString("NoDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Patreon Found!.
        /// </summary>
        public static string NoPatreon {
            get {
                return ResourceManager.GetString("NoPatreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wiki Found!.
        /// </summary>
        public static string NoWiki {
            get {
                return ResourceManager.GetString("NoWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Install Location not found!.
        /// </summary>
        public static string PathError1 {
            get {
                return ResourceManager.GetString("PathError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience mod loading issues, please contact Bonesy in Discord.
        /// </summary>
        public static string PathError2a {
            get {
                return ResourceManager.GetString("PathError2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Install Locations found!.
        /// </summary>
        public static string PathError2b {
            get {
                return ResourceManager.GetString("PathError2b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon.
        /// </summary>
        public static string Patreon {
            get {
                return ResourceManager.GetString("Patreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Mod.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Regen.
        /// </summary>
        public static string Regen {
            get {
                return ResourceManager.GetString("Regen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReMoDDeD.
        /// </summary>
        public static string ReMoDDeD {
            get {
                return ResourceManager.GetString("ReMoDDeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Character.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respec.
        /// </summary>
        public static string Respec {
            get {
                return ResourceManager.GetString("Respec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune Icons Only.
        /// </summary>
        public static string Rune_Icons_Only {
            get {
                return ResourceManager.GetString("Rune Icons Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rune Display.
        /// </summary>
        public static string RuneDisplay {
            get {
                return ResourceManager.GetString("RuneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runeword Sorting.
        /// </summary>
        public static string RWSort {
            get {
                return ResourceManager.GetString("RWSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        public static string SaveFiles {
            get {
                return ResourceManager.GetString("SaveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortened Levels.
        /// </summary>
        public static string ShortLevels {
            get {
                return ResourceManager.GetString("ShortLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will allow you to use Vanilla++ shortened levels or revert to default.
        /// </summary>
        public static string ShortLevelsDesc {
            get {
                return ResourceManager.GetString("ShortLevelsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assassin Charge Icons.
        /// </summary>
        public static string SinIcons {
            get {
                return ResourceManager.GetString("SinIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Icon Pack.
        /// </summary>
        public static string SkillIconPack {
            get {
                return ResourceManager.GetString("SkillIconPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Spawn Chance: .
        /// </summary>
        public static string SpawnChance {
            get {
                return ResourceManager.GetString("SpawnChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Stash.
        /// </summary>
        public static string Stash {
            get {
                return ResourceManager.GetString("Stash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string StashApply {
            get {
                return ResourceManager.GetString("StashApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StashCancel {
            get {
                return ResourceManager.GetString("StashCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please edit your tab names below:.
        /// </summary>
        public static string StashLabel {
            get {
                return ResourceManager.GetString("StashLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized Stash Tabs.
        /// </summary>
        public static string StashTabs {
            get {
                return ResourceManager.GetString("StashTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string StashTabsBtn {
            get {
                return ResourceManager.GetString("StashTabsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash Tab Names have been updated successfully!.
        /// </summary>
        public static string StashTabsSuccess {
            get {
                return ResourceManager.GetString("StashTabsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore Stash unlocked!\nYou now have 7 shared tabs in-game.
        /// </summary>
        public static string StashUnlockHard {
            get {
                return ResourceManager.GetString("StashUnlockHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softcore Stash unlocked!\nYou now have 7 shared tabs in-game.
        /// </summary>
        public static string StashUnlockSoft {
            get {
                return ResourceManager.GetString("StashUnlockSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softcore Stash already unlocked!.
        /// </summary>
        public static string StashUnlockSoftDone {
            get {
                return ResourceManager.GetString("StashUnlockSoftDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcore Stash already unlocked!.
        /// </summary>
        public static string StashUnlockSoftHard {
            get {
                return ResourceManager.GetString("StashUnlockSoftHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Telekinesis.
        /// </summary>
        public static string SuperTK {
            get {
                return ResourceManager.GetString("SuperTK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superuniques Always Drop.
        /// </summary>
        public static string Superuniques_Always_Drop {
            get {
                return ResourceManager.GetString("Superuniques Always Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Language.
        /// </summary>
        public static string TextLang {
            get {
                return ResourceManager.GetString("TextLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Theme.
        /// </summary>
        public static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Mod Updates.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up mod files....
        /// </summary>
        public static string UpdateBackup {
            get {
                return ResourceManager.GetString("UpdateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod not downloaded yet; nothing to backup!.
        /// </summary>
        public static string UpdateBackupError {
            get {
                return ResourceManager.GetString("UpdateBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning update process....
        /// </summary>
        public static string UpdateBegin {
            get {
                return ResourceManager.GetString("UpdateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Mod Files....
        /// </summary>
        public static string UpdateProgress1 {
            get {
                return ResourceManager.GetString("UpdateProgress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Complete! Ready to Play!.
        /// </summary>
        public static string UpdateProgressDone {
            get {
                return ResourceManager.GetString("UpdateProgressDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github link detected, performing additional folder management operations.
        /// </summary>
        public static string UpdateProgressGH {
            get {
                return ResourceManager.GetString("UpdateProgressGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download has started; but unable to determine file size.
        /// </summary>
        public static string UpdateProgressGHSize {
            get {
                return ResourceManager.GetString("UpdateProgressGHSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Updates Not Supported.
        /// </summary>
        public static string UpdatesOff {
            get {
                return ResourceManager.GetString("UpdatesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Vault.
        /// </summary>
        public static string Vault {
            get {
                return ResourceManager.GetString("Vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Config Data.
        /// </summary>
        public static string VaultFiles {
            get {
                return ResourceManager.GetString("VaultFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Update Available!.
        /// </summary>
        public static string VaultUpdateRdy {
            get {
                return ResourceManager.GetString("VaultUpdateRdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Version:.
        /// </summary>
        public static string Version1 {
            get {
                return ResourceManager.GetString("Version1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version:.
        /// </summary>
        public static string Version2 {
            get {
                return ResourceManager.GetString("Version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Update Available!.
        /// </summary>
        public static string VersionRdy {
            get {
                return ResourceManager.GetString("VersionRdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Use direct download link of .zip file.
        /// </summary>
        public static string Warning1 {
            get {
                return ResourceManager.GetString("Warning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Folder structure inside zip should be: ModName/ModName.mpq.
        /// </summary>
        public static string Warning2 {
            get {
                return ResourceManager.GetString("Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Can also extract manually to main D2R Folder/Mods.
        /// </summary>
        public static string Warning3 {
            get {
                return ResourceManager.GetString("Warning3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
